### ISSUE TITLE
Installation issues in windows 7

### ISSUE THREAD

**Issue by llcc** [tkf/emacs-jedi#148]
Dear tkf,

I have installed jedi for many times, however, never made it. So i have to come here to ask for your help. 

I have installed all the requirements as need in your manual. When i used `jedi:install-server` command to automatically configure jedi, the command always stopped at  
`Running: pip install --upgrade .....\jedi..` as below, and give me a deferred timeout error.

![image](https://f.cloud.github.com/assets/3996879/2473362/bf3704c0-b040-11e3-80f7-5cc56851c896.png)

sometimes like this

![image](https://f.cloud.github.com/assets/3996879/2473517/fabd6d4e-b041-11e3-81c9-b6e2fca53062.png)

I tried to set the EPC server manually with 'C:/Anaconda/Scripts/jediepcserver.py', unfortunately still no working. So what could the problem be?

And i tried to install the concurrent.el, but i can not find the command `jedi:make-env`. 
Please help me! Thank you.

**Comment by deadlytackler5** [comment]
Dear tkf,
Am not sure whether this is the right place to ask this but am sure you can hence this post...Downloaded Jedi.el via M-x list-packages also downloaded epc rest were automatically downloaded along with jedi. already have autocomplete..
Started with `M-x jedi:install-server`
it responded with-
    `python-environment--make-with-runner: Program named "virtualenv" does not exist.`
... so downloaded pyvenv.el, which again wanted to know the directory address. Assuming it wants the address of some virtualenv created virtual environment through cmd.exe with command- 
`c:\Python34\python -m pyvenv akkenv` 
which created a directory (akkenv)at - 
`C:\Windows\System32`
Installed Pyvenv.el through M-x list-package tried to activate it through `Mx pyvenv-activate` showed him akkenv however it seems he wants to go further deep down...where should I lead him to? 
My akkenv directory shows following folders
    `Include`
   `Lib`
   `Scripts`
    `pyvenv.cfg (which is not accessible when I am pointing towards it in minibuffer)`
my .emacs related to jedi is something like this at present - 
```
;;Jedi
(require 'jedi)
(setq jedi:server-command "~/.emacs.d/jediepcserver.py")
(add-hook 'python-mode-hook 'jedi:setup)
(setq python-environment-virtualenv "C:/Windows/System32/arunenv")
;; Hook up to autocomplete
(add-to-list 'ac-sources 'ac-sources-jedi-direct)
;; Enable for python-mode
;;(add-hook 'python-mode-hook 'jedi:setup)
;; python-interpreter
(setq python-shell-interpreter "C:/Python34/python.exe")

;; EPC for Jedi
(require 'epc)

;; Local Jedi keybindings
(defun jedi-config:setup-keys ()
  (local-set-key (kbd "M-.") 'jedi:goto-definition)
  (local-set-key (kbd "M-,") 'jedi:goto-definition-pop-marker)
  (local-set-key (kbd "M-?") 'jedi:show-doc)
  (local-set-key (kbd "M-/") 'jedi:get-in-function-call))

  (add-hook 'python-mode-hook 'jedi-config:setup-keys)
  ;; Never show in-function call automatically
  (setq jedi:get-in-function-call-delay 10000000)
  ;; Complete when type a dot
  (setq jedi:complete-on-dot t)
```

also output of certain commands are like this -
*** `M-: jedi:server-command`
**** `"C:\Users\arun\AppData\Roaming\emacs.d\jediepcaerver.py"`
*** `M-! C:\Users\arun\AppData\Roaming\emacs.d\jediepcaerver.py --help`
**** `opening help file`
as I have created a hardlink for jediepcserver.py at present location from jedi-core/jediepcserver.py

Where am I faulting ?
