### ISSUE TITLE
Program named "virtualenv" does not exist.

### ISSUE THREAD

**Issue by JM00oo** [tkf/emacs-jedi#158]
Hi,

I run the command M-x jedi:install-server, and I got the error message:
python-environment--make-with-runner: Program named "virtualenv" does not exist. 
I am sure virtualenv can be run in terminal.
Mac OS 10.9.2, Emacs 24.3
Please tell me how to fix it.
Thank you very much.

**Comment by MPBagger** [comment]
@hjmeric 

How did you manage to make the install process work? You said it was hanging at 
Running: pip install --upgrade /Users/EricHuang/.emacs.d/elpa/jedi-20140321.1323/...

I am facing the same problem now...

**Comment by ZelphirKaltstahl** [comment]
Does this mean that `emacs-jedi` is a no go, if there is no `virtualenv`? I am using `conda` and created a separate conda environment, in which I installed `jedi`. I've set `(setq py-python-command "/home/xiaolong/apps/anaconda3/envs/emacs-env/bin/python")`, so whatever uses `python` should have access to all installed packages in that environment.

Why is the command `virtualenv` assumed to exist?

Can I even use `emacs-jedi` with anaconda?

**Comment by jwhendy** [comment]
Just ran into this myself. On arch linux, `python2-virtualenv` creates `/usr/bin/virtualenv2` due to its default being `python3`. I ended up creating a symlink. Just adding a comment to the possible reasons one might not have `virtualenv` in path.
