### ISSUE TITLE
How to use my project's virtualenv?

### ISSUE THREAD

**Issue by Cheukyin** [tkf/emacs-jedi#172]
Jedi by default uses the virtualenv in .emacs/ 
But what should I do if I want to use the virtualenv of my project instead of the default one?

**Comment by talwrii** [comment]
If you want to use a virtualenv with a particular path (it's quite common practice to keep a virtualenv in a project). Then you can use:

```
(venv--activate-dir "$PATH_TO_VIRTUALENV")
```
