### ISSUE TITLE
UTF-8 decoding problems on jedi:goto-definition

### ISSUE THREAD

**Issue by abingham** [tkf/emacs-jedi#181]
When I try to `goto-definition` for some symbols, I get errors related to UTF-8 decoding. It appears that jedi (or some part of the machinery) is reading the contents of a shared library, doesn't realize that it's not source code, and is trying to decode it. I say this because a) this only seems to happen with symbols defined in native libraries and b) the string displayed in the message window appears to be the contents of a shared library.

The real problem from my point of view isn't that I'm not taken to the definition. Obviously this won't happen with native libraries in any event. But when this happens, the entire error message is displayed in the echo area, and since the error includes the contents of a shared library it's big and disruptive. Ideally jedi would either avoid this problem entirely by not trying to read binary files, or it would detect decoding errors more proactively and display a nicer message.

This problem also happens with `show-doc`. In that case, functionality actually *is* broken because, unlike `goto-definition`, I should still be able to get a docstring from a native library.

**Comment by syohex** [comment]
Sorry very too late reply. Would you show us sample code for reproduce this issue ?

**Comment by abingham** [comment]
It appears that this may be fixed now, though I'm not 100% sure. It will take me some time to verify, hopefully some time today.

**Comment by abingham** [comment]
OK, it looks like this problem has been fixed. At least, I can't replicate what I was seeing, so that's good enough for me :) I'll close this, and if the problem re-appears I'll open a new issue. Thanks!
