### ISSUE TITLE
Deffered Error

### ISSUE THREAD

**Issue by ghost** [tkf/emacs-jedi#183]
deferred error : (error Keyword argument :triggered not one of (:requires :force-init))

 shows in a minibuffer every time I try to use C-TAB or anything like that.
Does anyone know why??

Latest version of emacs , jedi and auto complete.

**Comment by immerrr** [comment]
FTR, no auto-complete is not necessary to use jedi in Emacs. The current version is split into two packages, `jedi-core` provides communication with the jediepcserver on top of which you can either use `jedi` or `company-jedi` that runs with auto-complete and company respectively. If you use `package-install`, you can just install `jedi` or `company-jedi` and let it ensure `jedi-core` is installed automatically.

Regarding the issue, it looks like a configuration issue. Please, try (re-)installing the current master to see if it persists.

**Comment by egarrulo** [comment]
As I am not programming in Python anymore, I cannot provide feedback. Thanks anyway for your assistance.
