### ISSUE TITLE
Melpa (with emacs24.3) installs 0.7.0 - old versioned jedi

### ISSUE THREAD

**Issue by madhavan020985** [tkf/emacs-jedi#186]
My pip installed jedi is versioned 0.8.1-final0. whereas, melpa jedi install has put version = 0, 7, 0 jedi in my .emacs folder. How can i use latest version jedi inside emacs?
Why i need this?
i am debugging an issue that /usr/local/lib/python2.7/dist_packages are not added to jedi's syspath. so i found that the code related to python import path is sitting in jedi/evaluate/sys_path#get_sys_path in pip installed jedi. Now, when i checked my melpa installed jedi code, it doesn't have any folder called as jedi/evaluate. so, i am clueless about how to check the entries in jedi's syspath...

**Comment by syohex** [comment]
I can install latest jedi on clean environment.

My step is
1. Remove virtualenv directory. `rm -rf ~/.emacs.d/.python-environments`
2. Launch Emacs. `emacs`
3. Install dependencies `M-x jedi:install-server`

This is output of `jedi:show-version-info`. jedi 0.8.1-final0 is installed.
```
(:emacs-version "25.0.50.3" :jedi-version "0.2.0alpha2")
((:version "2.7.8 (default, Oct 20 2014, 15:05:19) \n[GCC 4.9.1]" :name "sys" :file nil)
 (:version "0.8.1-final0" :name "jedi" :file "/home/syohei/.emacs.d/.python-environments/default/local/lib/python2.7/site-packages/jedi/__init__.pyc")
 (:version "0.0.5" :name "epc" :file "/home/syohei/.emacs.d/.python-environments/default/local/lib/python2.7/site-packages/epc/__init__.pyc")
 (:version "0.0.3" :name "sexpdata" :file "/home/syohei/.emacs.d/.python-environments/default/local/lib/python2.7/site-packages/sexpdata.pyc"))
```

Would you retry after removing `~/.emacs.d/.python-environments` ?

**Comment by madhavan020985** [comment]
hi, the version got upgraded syo... but as i mentioned earlier, the print statements i put in python code don't come in emacs message buffer. In one javascript project, i use tern.js extensively with emacs. Tern.js has a similar arch like jedi except that ternjs has a http server whereas jedi has a rpc server  i can talk to tern service using http client as curl (or) for collecting logs & i can debug terncode. in the same way, how can i put logs in my jedi code & understand the source code better... thanks for looking into it, syo...

**Comment by madhavan020985** [comment]
jedi:pop-to-epc-buffer did the charm... it takes you to the python server process buffer. thanks for you all..

**Comment by syohex** [comment]
This is related to #184.

**Comment by syohex** [comment]
@madhavan020985 Please use latest version and retry. You can download jedi `0.8.1`
with it.

**Comment by madhavan020985** [comment]
@syohex, the logs will go into process-buffer and not into message buffer as i expected. so, i see no issues at present. it is just that, i was searching for logs in the wrong place.
