### ISSUE TITLE
Jedi on Aquamacs

### ISSUE THREAD

**Issue by sshnip** [tkf/emacs-jedi#188]
Hi there. So at first, I use os x and aquamacs, not GNU Emacs for os X. Aquamacs has some annoying bugs fixed.
So I've installed latest available version from melpa package repo. When I try to launch jedi:setup I see this error:
> Source file `/Users/user/Library/Preferences/Aquamacs Emacs/Packages/elpa/jedi-20140321.1323/jedi.el' newer than byte-compiled file
> deferred error : (error "Server may raise an error. Use \"M-x epc:pop-to-last-server-process-buffer RET\" to see full traceback:
> Traceback (most recent call last):
>  File \"/Users/user/Library/Preferences/Aquamacs Emacs/Packages/elpa/jedi-20140321.1323/jediepcserver.py\", line 314, in <module>
    main()
  File \"/Users/user/Library/Preferences/Aquamacs Emacs/Packages/elpa/jedi-20140321.1323/jediepcserver.py\", line 310, in main
    jedi_epc_server(**vars(ns))
  File \"/Users/user/Library/Preferences/Aquamacs Emacs/Packages/elpa/jedi-20140321.1323/jediepcserver.py\", line 214, in jedi_epc_server
    import epc.server
ImportError: No module named epc.server
")

When I try to launch jedi:install-server I see next error:
> Running: pip install --upgrade /Users/user/Library/Preferences/Aquamacs Emacs/Packages/elpa/jedi-20140321.1323/...Done
> deferred error : (error "Process [/Users/user/Library/Preferences/Aquamacs Emacs/Packages/.python-environments/default/bin/pip] exited abnormally : /Applications/Aquamacs.app/Contents/MacOS/Aquamacs: /Users/user/Library/Preferences/Aquamacs Emacs/Packages/.python-environments/default/bin/pip: No such file or directory
")

I think the line _/Applications/Aquamacs.app/Contents/MacOS/Aquamacs:_ tells that somewhere space character confuses function calls or something like that

**Comment by syohex** [comment]
Do you install `virtualenv` and `pip` ?

**Comment by sshnip** [comment]
I've installed virtualenv support for Emacs from MELPA and installed pip for system-wide python.

**Comment by paraita** [comment]
I encounter the same error as you sshnip (on jedi-20150109.2230)

**Comment by syohex** [comment]
> /Applications/Aquamacs.app/Contents/MacOS/Aquamacs: /Users/user/Library/Preferences/Aquamacs Emacs/Packages/.python-environments/default/bin/pip: No such file or directory

@sshnip You got above message. It looks that `pip` is not installed in your virtualenv directory.

**Comment by sshnip** [comment]
@syohex not true, idd there's /Users/user/Library/Preferences/Aquamacs Emacs/Packages/.python-environments/default/bin/pip file. I'll repeat, the problem is likely this line
>/Applications/Aquamacs.app/Contents/MacOS/Aquamacs:
What is that? It's not executable. You can see the same result if you compare the output for next commands:
>$ cd /Users/user/Library/Preferences/Aquamacs Emacs/Packages/.python-environments/default/bin/
and
>$ cd "/Users/user/Library/Preferences/Aquamacs Emacs/Packages/.python-environments/default/bin/"

**Comment by paraita** [comment]
I'll try to wrap `(convert-standard-filename jedi:source-dir)` in a string with the "\"" chars tonight using concat.

**Comment by sshnip** [comment]
@paraita thank you! Can't wait for solution for this issue :)

**Comment by paraita** [comment]
@sshnip my solution didn't work. I think that the problem lies in the python-environment module (look for the python-environment-run func, it never sanitize the command).
I ended up setting the jedi:environment-root var to my ~/.emacs.d/jedi-env folder.
To do that: M-x, then customize-variable <enter>, then jedi:environment-root <enter>, then an existing path. You can then call the jedi:install-server command.

**Comment by sshnip** [comment]
@paraita thank you very much. Not fix but good workaround. THe last question is, how can we help to fix this problem? Where should I report issue?
Thanks

**Comment by syohex** [comment]
Would you tell me how to install `jedi` ?
I can't reproduce this issue with Aquamacs and `package.el`.
I want to reproduce this issue on my machine.

**Comment by paraita** [comment]
@sshnip I think we can open an issue on the [emacs-python-environment](https://github.com/tkf/emacs-python-environment) page.
@syohex do you mean the jedi module ? if that's so:
`pip install jedi`

**Comment by sshnip** [comment]
@syohex yep, as @paraita said, it's ***pip install jedi*** + emacs-jedi from MELPA

**Comment by ljofre** [comment]
run this line
python /Users/user/Library/Preferences/Aquamacs Emacs/Packages/elpa/jedi-20140321.1323/jediepcserver.py

if you get the same error, the problem is the epc installation
you will need to install epc
pip install epc

**Comment by nicholascarroll** [comment]
Hi I am also having this error 

> /Users/user/Library/Preferences/Aquamacs Emacs/Packages/.python-environments/default/bin/pip: No such file or directory

And this did not happen on Yosemite only now on El Capitan.

**Comment by syohex** [comment]
AquaEmacs package directory is `~/Library/Preferences/Aquamacs Emacs/Packages/` which contains space in its path. `jedi:install-server` installs needed commands under there with virtualenv. Then shebang of commands like this. (BTW shebang is generated by virtualenv)

```python
#!"/Users/syohei/Library/Preferences/Aquamacs Emacs/Packages/.python-environments/default/bin/pip"
```

MacOSX treats this that command intepreter is `/Users/syohei/Library/Preferences/Aquamacs` because MacOSX cannot handle space. And MacOSX raises `no such file`.

This is AquaEmacs issue and not jedi issue.

You can fix this issue by

1. Rewrite `pip` shebang like `#!/usr/bin/env python`
2. Change package directory whose path does not contain any spaces
