### ISSUE TITLE
Print statements in jediepcserver.py breaks epc:start-server

### ISSUE THREAD

**Issue by madhavan020985** [tkf/emacs-jedi#189]
print statements for logging in jediepcserver.py breaks the emacs setup. By default, once emacs starts jedi server process through epc:start-server, it expects a string that contains port number - 
````elisp
(string-match "^[ \n\r]*[0-9]+[ \n\r]*$" port-str)
````
But, when i put prints in my python module, the string read from process buffer is not of a familiar pattern to emacs plugin & it barfs, 
````elisp
(error "Server may raise an error. \
Use \"M-x epc:pop-to-last-server-process-buffer RET\" \
to see full traceback:\n%s" port-str)
````
here port-str is replaced with my log print msgs.... 
Can't there be a better mechanism (or) status code from the server code to monitor its status, than looking for a pattern in the log message?

**Comment by syohex** [comment]
This is `epc` specification, not `emacs-jedi`.

Why did you insert `print` in jediepcserver.py ?
I suppose you should log to the file instead of outputing to stdout or stderr.
