### ISSUE TITLE
Large completion sets appear to fail.

### ISSUE THREAD

**Issue by mahuron** [tkf/emacs-jedi#191]
Running Emacs 24.4.1 built from Homebrew, jedi 20150109.2230, popup 20150116.1223, epc 20140609.2234.

I enabled jedi:complete-on-dot only to find that it did not appear to have any effect.  After digging a bit, I found that the jedi server does indeed send a large reply and the data ends up in jedi:complete-request.  Unfortunately, it never results in a popup.  A manual jedi:complete (C-tab) has no visual response.  Once I type a few characters past the dot (e.g. 'os.ex<C-tab>'), the popup works as expected.

**Comment by simonpp** [comment]
Same issue here.  jedi:complete-on-dot does not show any completion candidates until I type a few characters. It used to work until recently.  I believe it has to do with an update of auto-complete, approx two weeks ago. I'm sorry that I'm not able to provide more detailed information.
When I put the cursor after a dot and call M-x ac-complete-jedi-direct the popup with the completion candidates shows up.
I'm running emacs 24.4.1 on linux , jedi 20150109.2230, popup 20150116.1223, epc 20140609.2234, auto-complete 20150124.1523 (all latest versions from melpa).
Auto-completion via jedi in vim is still working.

**Comment by syohex** [comment]
Would you us sample code of this issue ?

**Comment by mahuron** [comment]
It's quite simple:

import os
os.<C-tab>

I hadn't considered auto-complete's role in all this but I will see if a rollback will resolve.

**Comment by syohex** [comment]
This is `auto-complete` bug which is already fixed.
Please upgrade `auto-complete`. It works now as below.

![jedi](https://cloud.githubusercontent.com/assets/554281/6001909/e31a4298-ab31-11e4-8798-8d3feffc35a9.png)

**Comment by mahuron** [comment]
Spot on.  Thank you.
