### ISSUE TITLE
Change keybindings

### ISSUE THREAD

**Issue by nayefc** [tkf/emacs-jedi#196]
I installed Jedi mode in Emacs. I noticed that it overrides `C-c .` and `C-c ,` (`goto-definition` and `goto-definition-pop-marker respectively`).

Here is how I set it up in my init file:

```lisp
    (setq jedi:setup-keys t)
    (add-hook 'python-mode-hook 'jedi:setup)
```

I am using another mode called multiple-cursors that is set up as follows:

```lisp
    (add-to-list 'load-path "~/.emacs.d/multiple-cursors.el/")
    (global-set-key (kbd "C-c .") 'mc/mark-next-like-this)
    (global-set-key (kbd "C-c ,") 'mc/mark-previous-like-this)
```
Once jedi-setup loads, it rebinds my `C-c .` and `C-c ,`. What I'd like to do is keep my multiple cursors bindings and remap Jedi's bindings. I tried adding this to the end of my Jedi setup but it ends up mapping the Jedi functions to both C-c./, and C-c j/k at the same time.
```lisp
    (setq jedi:key-goto-definition (kbd "C-c k"))
    (setq jedi:key-goto-definition-pop-marker (kbd "C-c j"))
```
The reason this happens is because Jedi binds them on the regular C-c ./, mappings, then just adds another C-c j/k mapping.

When I use `define-key`, it does not work. Here is what I did:

```lisp
(eval-after-load 'jedi-mode
   '(progn
      (define-key jedi-mode-map (kbd "C-c d") nil))) 
```

This has no effect. When I remove `progn`, I get a symbol void error.
How do I stop Jedi from completely not binding to the C-c ./, and only bind to C-c j/k?

**Comment by syohex** [comment]
Would you try with following configuration ?

```lisp
(eval-after-load 'jedi
  '(progn
     (define-key jedi-mode-map (kbd "C-c .") nil)
     (define-key jedi-mode-map (kbd "C-c ,") nil)))
```

`emacs-jedi` always set `"C-c ?"`, `"C-c ."`, `"C-c ,"` bindings, so if you want to use
these key bindings, you have to unset them.

PS: Your `eval-after-load` is wrong, you should use `'jedi` instead of `'jedi-mode`
as first argument.

**Comment by proofit404** [comment]
@syohex `eval-after-load` with quoted symbol doesn't work for me. Only `(eval-after-load "jedi"` works.  Is there any changes in its behavior depending on emacs version?

**Comment by syohex** [comment]
Hmm, quoted symbol works on Emacs 24.3 and development version.
Which version do you use ?

**Comment by proofit404** [comment]
It works with 24.4, maybe I meet this limitation in the earlier emacs versions.
Sorry for confusion.

**Comment by nayefc** [comment]
Yes, `"jedi"` fixed it for me.

**Comment by proofit404** [comment]
@nayefc what exactly emacs version are you use?

**Comment by nayefc** [comment]
Emacs for OS X 24.4.1.
