### ISSUE TITLE
Hide epc con buffers

### ISSUE THREAD

**Issue by Zack--** [tkf/emacs-jedi#199]
I use eMacs with a small number of buffers and I often switch between them and I find the `*epc con N*` buffers really annoying.

Is there a way to hide them (or get rid of them altogether) ?

**Comment by syohex** [comment]
(This is `emacs-epc` problem, not `emacs-jedi`.)

If you use `ido-mode`, you can use `ido-ignore-buffers` for this purpose.
If you use `iswitchb`, you can use `iswitchb-buffer-ignore`.

**Comment by Zack--** [comment]
I'm sorry if it was out of place, I figured a lot of ``jedi`` users might have faced the same need as me.

Thank you very much

**Comment by syohex** [comment]
This is another hack.

```lisp
(defadvice epc:make-procbuf (around foo activate)
  ad-do-it
  (with-current-buffer ad-return-value
    (rename-buffer (concat " " (buffer-name)))
    (setq ad-return-value (buffer-name))))
```

**Comment by Zack--** [comment]
Lisp is truly beautiful, thanks again !

**Comment by immerrr** [comment]
This issue looks resolved, closing.
