### ISSUE TITLE
`jedi:complete-on-dot` breaks evil-mode replace mode

### ISSUE THREAD

**Issue by jonathanj** [tkf/emacs-jedi#200]
When entering replace mode (by pressing `R`) in evil-mode the expected behaviour is that the character under the cursor is replaced by whatever character is typed. When `jedi:complete-on-dot` is non-nil then typing period (`.`) in replace mode *inserts* a period instead of replacing the current character under the cursor with a period.

Consulting `C-x h .` while in replace mode informs me that indeed it is `jedi:dot-complete` that is bound.

**Comment by syohex** [comment]
Thanks for report.
I fixed this issue at #201. Please check latest version.

**Comment by syohex** [comment]
@jonathanj  Please reopen this issue if you still have problem.
