### ISSUE TITLE
Jedi relies on unreleased version of python-environment

### ISSUE THREAD

**Issue by bastibe** [tkf/emacs-jedi#210]
I just updated jedi from melpa-stable. The file jedi-core.el requires python-environment 0.0.2, which is not available on melpa-stable or marmalade yet.

This makes Emacs raise an error on startup, and thus fail loading init.el.

**Comment by syohex** [comment]
Thanks for report. I tagged python-environment 0.0.2. Please retry after some hours later.

**Comment by bastibe** [comment]
Cool, thank you!
