### ISSUE TITLE
Jedi -0.2.1 doesn't take PYTHON_PATH from ~/.bashrc

### ISSUE THREAD

**Issue by madhavan020985** [tkf/emacs-jedi#211]
When i bring up emacs, jedi:goto-definition works good for pip installed libraries. But there are some python lib modules, i have added in $HOME/.bashrc. Jedi:emacs doesn't use this user's global shell variable - PYTHONPATH. And hence jedi:goto-definition fails to find the definition for functions sitting inside this custom path. 
Has jedi:emacs got any function (or) variable that will help me to check the python path during runtime, something like 
````python
jedi:python_libs
````
And also, if user wants to add custom locations to jedi's PYTHON_PATH, how can he do it? I had added it as a hack job during load-time in jediepcserver.py#jedi_epc_server()#sys_path... But i am looking for a cleaner way to do it...

**Comment by syohex** [comment]
I suppose you can use `(setenv "PYTHON_PATH"  "some_directory")` in your configuration file(like `~/.emacs.d/init.el`). It is easy to set environment variables same as shell by using [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell)

**Comment by madhavan020985** [comment]
it works with (exec-path-from-shell-copy-env "PYTHONPATH").... i owe a lot to you & the communiity, syohex....
