### ISSUE TITLE
Jedi doesn't show available methods for instances

### ISSUE THREAD

**Issue by tarjeiba** [tkf/emacs-jedi#212]
My configuration of jedi won't show available methods for an instance of a class, only for the class itself. The following will give no completion at the point

    import matplotlib.pyplot as plt

    fig = plt.figure()
    fig.

while a corresponding `plt.Figure` instead of `fig.` will show all available methods. Does anyone have an idea of what may be wrong?

**Comment by syohex** [comment]
This is a jedi(not `emacs-jedi`) issue. jedi does not complete such case. (jedi completes nothing,
so emacs-jedi shows nothing).

![jedi-matplotlib](https://cloud.githubusercontent.com/assets/554281/6777091/a4473d72-d189-11e4-8085-d513dbd4111b.png)

Following screenshot is when jedi completes some candidates. (Usually jedi completes
like this).

![jedi-usually](https://cloud.githubusercontent.com/assets/554281/6777128/e9fb7a68-d189-11e4-8d58-48c90ea6f5e9.png)

**Comment by tarjeiba** [comment]
Thanks, @syohex, I'll issue it in the jedi repo.
