### ISSUE TITLE
variable is void: html

### ISSUE THREAD

**Issue by nyoungb2** [tkf/emacs-jedi#216]
I installed emacs-jedi on my Ubuntu server with el-get. The installation seemed to work, but every time I try to run a jedi command (e.g., jedi:install-server or jedi:start-dedicated-server), I get the error message: "Symbol's value as variable is void: html". I tried manually installing the Python server with the setup.py, and it seemed to work, but I'm still getting the 'void: html' error.

Any idea on what's wrong?

**Comment by syohex** [comment]
I suppose installation is failed(Recently github.com is very unstable.).

Would you check content of jedi.el and jedi-core.el ?
(I suppose there are under `~/.emacs.d/el-get/emacs-jedi/`)

If they are HTML, the installation was failed.
And please reinstall emacs-jedi again.

**Comment by nyoungb2** [comment]
I think the problem was caused by a previous failed install with package.el. I removed all jedi-associated files and reinstalled via el-get. Now, everything seems to working. Thank you for the help!

**Comment by syohex** [comment]
You are welcome.
