### ISSUE TITLE
Weird indentation after two levels

### ISSUE THREAD

**Issue by computersarecool** [tkf/emacs-jedi#220]
This code:
```
def go (dict) {
    for k, v in dict:
        print(k, v) #Pressing tab would only de-indent (or make level with the for)
}
```

caused problems with indentation. Jedi only de-indents when I press tab

**Comment by syohex** [comment]
I think this is python-mode issue, not `emacs-jedi`.

**Comment by computersarecool** [comment]
Ah, it was a problem with my code. Those use of curly braces must have thrown it off.
