### ISSUE TITLE
new jedi fails to use popup in right width

### ISSUE THREAD

**Issue by oracleyue** [tkf/emacs-jedi#226]
It always like the figure shown. It fails to use the correct width automatically, no matter how big the window is. I cannot see the description of the function.

Could anyone tell me some scripts in .emacs to fix it? I remember years ago, there were some settings to fix it. Later the bug disappeared.
Versions:
emacs: 24.4
jedi for emacs: jedi-core, 20150413-520; jedi, 2015-0413;
popup for emacs: 20150315.612
jedi for python: 0.8.1

![screen shot 2015-04-24 at 17 58 21](https://cloud.githubusercontent.com/assets/5046605/7323018/1c9902a2-eaac-11e4-81ed-cc4548f5ed5d.png)

**Comment by syohex** [comment]
Sorry very too late reply. Please add following configuration and try again.

```lisp
(setq ac-max-width 0.5)
````

If you want to use it only python-mode, please define it as buffer local variable.
```lisp
(defun my/python-mode-hook ()
  (setq-local ac-max-width 0.5))
(add-hook 'python-mode-hook 'my/python-mode-hook)
```

**Comment by oracleyue** [comment]
@syohex  Thanks a lot! That's the configuration I want! I used it once before, but someday deleted it. Thx!!
