### ISSUE TITLE
revert-buffer is broken in jedi-mode

### ISSUE THREAD

**Issue by stakemori** [tkf/emacs-jedi#234]
Hi. First, thank you for writing this useful package.

It seems that `jedi` breaks `revert-buffer`.
I checked this in Emacs 24.5 (emacs -q) with only `jedi` installed via MELPA.
I don't understand why `jedi` breaks `revert-buffer`, but I can reproduce it by the following code.

    (defun my/test-revert-buffer ()
      (let ((file (expand-file-name "foo.py" temporary-file-directory))
            (file-content1 "# -*- coding: utf-8 -*-

    '''
    Foo.
    '''
    ")
            (file-content2 "# -*- coding: utf-8 -*-

    class Foo(object):
        pass
    "))
        (write-region file-content1 nil file nil 'silent)
        (find-file file)
        ;; The content of the current buffer is equal to file-content1.

        (write-region file-content2 nil file nil 'silent)
        (revert-buffer nil t)
        ;; Now the content of the current buffer should be equal to file-content2.
        (cl-assert (string= (buffer-string) file-content2))))

    (my/test-revert-buffer)

I use Ubuntu 14.04 and my Emacs configuration in the test is following:

    (when load-file-name
      (setq user-emacs-directory (file-name-directory load-file-name)))
    (require 'package)
    (setq package-archives
          (append package-archives
                  '(("melpa" . "http://melpa.org/packages/")
                    ("marmalade" . "http://marmalade-repo.org/packages/"))))
    (package-initialize)

    (add-hook 'python-mode-hook 'jedi:setup)
    (setq jedi:complete-on-dot t)

**Comment by nbecker** [comment]
I found (and reported on emacs) that revert-buffer was (badly) broken.  I
suspected jedi but never verified that.

On Sat, May 23, 2015 at 8:04 AM, Sho Takemori <notifications@github.com>
wrote:

> Hi. First, thank you for writing this useful package.
>
> It seems that jedi breaks revert-buffer.
> I checked this in Emacs 24.5 (emacs -q) with only jedi installed via
> MELPA.
> I don't understand why jedi breaks revert-buffer, but I can reproduce it
> by the following code.
>
> (defun my/test-revert-buffer ()
>   (let ((file (expand-file-name "foo.py" temporary-file-directory))
>         (file-content1 "# -*- coding: utf-8 -*-
>
>
> '''
> Foo.
> '''
> ")
>         (file-content2 "# -*- coding: utf-8 -*-
>
> class Foo(object):
>     pass
> "))
>     (write-region file-content1 nil file nil 'silent)
>     (find-file file)
>     ;; The content of the current buffer is equal to file-content1.
>
>     (write-region file-content2 nil file nil 'silent)
>     (revert-buffer nil t)
>     ;; Now the content of the current buffer should be equal to file-content2.
>     (cl-assert (string= (buffer-string) file-content2))))
>
> (my/test-revert-buffer)
>
> I use Ubuntu 14.04 and my Emacs configuration in the test is following:
>
> (when load-file-name
>   (setq user-emacs-directory (file-name-directory load-file-name)))
> (require 'package)
> (setq package-archives
>       (append package-archives
>               '(("melpa" . "http://melpa.org/packages/")
>                 ("marmalade" . "http://marmalade-repo.org/packages/"))))
> (package-initialize)
>
> (add-hook 'python-mode-hook 'jedi:setup)
> (setq jedi:complete-on-dot t)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tkf/emacs-jedi/issues/234>.
>



-- 
*Those who don't understand recursion are doomed to repeat it*

**Comment by stakemori** [comment]
Are you referring to [this](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=20440) ? Thanks for the information.

If I add `(remove-hook 'after-change-functions 'jedi:after-change-handler t)`
to `my/test-revert-buffer` above, then no error occurs. So I think something is wrong with `jedi:after-change-handler`. Or `jedi` uses functions of Emacs in a right way, but Emacs has a bug.

**Comment by nbecker** [comment]
I find that revert-buffer is giving corrupted buffers - they appear to have
chunks of data spliced out-of-order.  I did NOT test whether jedi is
causing this - but it is a possibility.

On Sun, May 24, 2015 at 11:21 PM, Sho Takemori <notifications@github.com>
wrote:

> Are you referring to this
> <https://debbugs.gnu.org/cgi/bugreport.cgi?bug=20440> ? Thanks for the
> information.
>
> If I add (remove-hook 'after-change-functions 'jedi:after-change-handler
> t)
> to my/test-revert-buffer above, then no error occurs. So I think
> something is wrong with jedi:after-change-handler. Or jedi uses functions
> of Emacs in a right way, but Emacs has a bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tkf/emacs-jedi/issues/234#issuecomment-105112503>.
>



-- 
*Those who don't understand recursion are doomed to repeat it*

**Comment by stakemori** [comment]
If `jedi:after-change-handler` causes this, the following code will fix the problem.

    (add-hook 'jedi-mode-hook
              (lambda () (remove-hook 'after-change-functions
                                      'jedi:after-change-handler t)))

**Comment by thomasf** [comment]
I guess that technically this issue really isn't solved, just avoided for a specific setting of of edi:install-imenu... Helped me find the issue anyway so thats, have been seeing this on and off for a very long time now...
