### ISSUE TITLE
M-x jedi:install-server is stuck

### ISSUE THREAD

**Issue by MPBagger** [tkf/emacs-jedi#241]
Hi

I am trying to install jedi using the command M-x jedi:install-server and it seems to start out fine, but then it is stuck at the message:

Running: pip install --upgrade /Volumes/DISK/.emacs.d/elpa/jedi-core-20150623.2335/...

I am running  Emacs 24.5.1 on Mac OS X 10.10.3.

I have followed the suggestions in https://github.com/tkf/emacs-jedi/issues/158 but now I am stuck.

Best,
Martin

**Comment by syohex** [comment]
Could you check whether pip command succeed in terminal ?
```
% pip install --upgrade /Volumes/DISK/.emacs.d/elpa/jedi-core-20150623.2335/
```

**Comment by MPBagger** [comment]
After updating pip to the latest version, it runs in terminal, but I am still having problems in emacs. It is still stuck.

(Normally I am using anaconda to control my python environment from the terminal.)

**Comment by syohex** [comment]
Hmm, I cannot reproduce on my mac with Python 2.7.6 and 2.7.10.

**Comment by noraderam** [comment]
FWIW, I'm having the same problem with OS X 10.8.5, using Aquamacs 3.0a GNU Emacs 24.3.50.2

**Comment by syohex** [comment]
Please install emacs-jedi dependencies(`jedi` and `epc`) in terminal(without `jedi:install-server`) and retry.

**Comment by MPBagger** [comment]
Can you tell me how to do that?

**Comment by MPBagger** [comment]
I just tried reinstalling everything :( still the same, but when I run `M-! which virtualenv` it returns `[No match]`. 

I have tried to reinstall virtualenv from the terminal and I have added the path (~/anaconda/bin/) inside my init.el. using the following code:

```
;;; Set localized PATH for OS X to be able to locate specific directories in emacs (specified in the list)
(defun my-add-path (path-element)
  "Add the specified PATH-ELEMENT to the Emacs PATH."
  (interactive "DEnter directory to be added to path: ")
  (if (file-directory-p path-element)
     (progn
       (setenv "PATH" (concat (expand-file-name path-element) path-separator (getenv "PATH")))
       (add-to-list 'exec-path (expand-file-name path-element)))))

(if (fboundp 'my-add-path)
   (let ((my-paths (list "~/anaconda/bin/" "/opt/local/bin" "/usr/local/bin" "/usr/local/bin/git" )))
      (dolist (path-to-add my-paths (getenv "PATH"))
         (my-add-path path-to-add))))
```
Any ideas?

**Comment by syohex** [comment]
I recommend you to install [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell) for that purpose.

**Comment by MPBagger** [comment]
Solved..

First I ran `pip uninstall jedi` and `pip uninstall epc`followed by `pip install jedi` and `pip install epc` from the terminal. 
Secondly I installed [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell) and added
```
(when (memq window-system '(mac ns))
  (exec-path-from-shell-initialize))
```
to the init.el. 
Finally I ran `pip install --upgrade /Volumes/DISK/.emacs.d/elpa/jedi-core-20150623.2335/` from the terminal, and now it works. No `M-x jedi:install-server``

Thank you @syohex

**Comment by kprojiang** [comment]
MPBagger's idea is a way out. I encounter the same problem, with epc, deferred, etc installed in emacs. I think exec-path-from-shell doesn't work in windows7, and only `pip install --upgrade ...` in cmd window works out right.
My command is `pip install --upgrade e:\.emacs.d\elpa\jedi-core-20170121.610\...`
