### ISSUE TITLE
Go to definition doesn't work for variables in function argument

### ISSUE THREAD

**Issue by sollidsnake** [tkf/emacs-jedi#242]
When I try to use `jedi:goto-definition` for a variable passed as a function argument, I get definition not found. I recorded I gif showing this issue:

![gifrecord_2015-08-04_112428](https://cloud.githubusercontent.com/assets/1778350/9063088/4ebdd830-3a9c-11e5-82ad-c15e519a1565.gif)

**Comment by syohex** [comment]
I suppose it is jedi issue, not emacs-jedi.

```
In [1]: import jedi

In [2]: source = '''test_var = 'hello'
   ...: 
   ...: test_var
   ...: 
   ...: print(test_var)
   ...: '''

In [3]: script = jedi.Script(source, 5, 7, '')

In [4]: defs = script.goto_assignments()

In [5]: len(defs)
Out[5]: 0
```

However it works if I pass another argument to print function.

```
In [1]: import jedi

In [2]: source = '''test_var = 'hello'
   ...: 
   ...: test_var
   ...: 
   ...: print(test_var, 1)
   ...: '''

In [3]: script = jedi.Script(source, 5, 7, '')

In [4]: defs = script.goto_assignments()

In [5]: [defs[0].line, defs[0].column]
Out[5]: [1, 0]
```

**Comment by sollidsnake** [comment]
I see... do you think should I report this issue to jedi?

**Comment by syohex** [comment]
Please
