### ISSUE TITLE
issue on completion when importing scipy

### ISSUE THREAD

**Issue by oracleyue** [tkf/emacs-jedi#243]
(I have known the intrinsic complicate issue in `scipy`, as indicated in https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/mMiv9QslB4E.)

Could you confirm the following problem of "jedi"? Is it a bug or just the way I misused python? Thanks!
 
`jedi` seems to have slightly problems in understanding the following `import` statement:
```python
from scipy import linalg
```
When I run `linalg.`, there is no regular functions in list, but certain ones like `__xxx__`. This is legal in python, which I have tested on completion in IPython. In addition, the following import also fails to work in `jedi`
```python
import scipy.linalg
scipy.linalg. (<--- no completion; valid in IPython completion)
```

I would not say it's a big bug, since `jedi` understands the other `import` style:
```python
import scipy.linalg as la
```
When I run `la.`, everything works fine. Currently I use `import scipy.linalg as linalg` as alternative to `from scipy import linalg`, whose style seems pretty odd. 
Moreover, `jedi` actually understand `from ... import ...` statement, e.g.
```python
from scipy.linalg import norm
```
When I use `norm()`, `jedi` gives the correct call signatures.

In a sum, it seems that problem only happens when using `from scipy import ...` to import subpackages (like `linalg`, `optimize`, etc.; these are actually directories, according to the webpage I attached at beginning).

May I ask whether there would be lots of work to make `jedi` understand `from scipy import linalg`?
Thanks a lot!

**Comment by syohex** [comment]
Hmm I cannot reproduce this issue.

![jedi](https://cloud.githubusercontent.com/assets/554281/9422246/09c0ca2e-48c7-11e5-9973-8e35228fd132.png)

**Comment by oracleyue** [comment]
@syohex 
According to the function list of `scipy.linalg`: http://docs.scipy.org/doc/scipy-0.15.1/reference/linalg.html,
none of them appears in your list (like `norm`, `eig`). Could you check your list?
However, if you `import scipy.linalg as la`, when you do `la.`, you got them. 
Could you see if you can reproduce these I mention here? Thanks!

**Comment by syohex** [comment]
I checked. `jedi` cannot get `scipy.linalg` methods.

```
% ipython
Python 3.4.3 (default, Mar 26 2015, 22:03:40) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import jedi

In [2]: source = '''import scipy.linalg
   ...: scipy.linalg.
   ...: '''

In [3]: script = jedi.Script(source, 2, len('scipy.linalg.'), 'example.py')

In [4]: completions = script.completions()

In [5]: completions
Out[5]: 
[<Completion: mro>,
 <Completion: __base__>,
 <Completion: __bases__>,
 <Completion: __basicsize__>,
 <Completion: __bool__>,
 <Completion: __call__>,
 <Completion: __class__>,
 <Completion: __delattr__>,
 <Completion: __dict__>,
 <Completion: __dictoffset__>,
 <Completion: __dir__>,
 <Completion: __doc__>,
 <Completion: __eq__>,
 <Completion: __flags__>,
 <Completion: __format__>,
 <Completion: __ge__>,
 <Completion: __getattribute__>,
 <Completion: __gt__>,
 <Completion: __hash__>,
 <Completion: __init__>,
 <Completion: __instancecheck__>,
 <Completion: __itemsize__>,
 <Completion: __le__>,
 <Completion: __lt__>,
 <Completion: __module__>,
 <Completion: __mro__>,
 <Completion: __name__>,
 <Completion: __ne__>,
 <Completion: __new__>,
 <Completion: __prepare__>,
 <Completion: __qualname__>,
 <Completion: __reduce__>,
 <Completion: __reduce_ex__>,
 <Completion: __repr__>,
 <Completion: __setattr__>,
 <Completion: __sizeof__>,
 <Completion: __str__>,
 <Completion: __subclasscheck__>,
 <Completion: __subclasses__>,
 <Completion: __subclasshook__>,
 <Completion: __text_signature__>,
 <Completion: __weakrefoffset__>]
```

**Comment by oracleyue** [comment]
@syohex Has this bug been fixed? Is it a bug of `jedi`?

**Comment by syohex** [comment]
> Has this bug been fixed?

No.

> Is it a bug of jedi?

Yes.

**Comment by oracleyue** [comment]
@syohex Okay, thanks!
