### ISSUE TITLE
Auto complete dependency

### ISSUE THREAD

**Issue by AndreaCrotti** [tkf/emacs-jedi#244]
I'm not using company-mode instead of auto-complete for everything.
So I wanted to change my Python settings as well to use it, but it turns out it's a hard dependency for Jedi now..

Is there a way to use company-mode instead of auto-complete for Jedi auto-completion?
Thanks

**Comment by syohex** [comment]
Please install [company-jedi](https://github.com/syohex/emacs-company-jedi).

**Comment by AndreaCrotti** [comment]
Thanks @syohex yes I tried that, and I didn't get it fully working yet but the real problem is that uninstalling auto-complete completely (if not using it) still makes emacs-jedi fail..

**Comment by syohex** [comment]
How do you install package ? If you use `package.el`, auto-complete is not installed by installing company-jedi. `company-jedi` installs `company`, `jedi-core` as its dependencies.

**Comment by syohex** [comment]
Please do not install `jedi` which is an auto-complete plugin of `jedi` and install only `company-jedi` for company users.
