### ISSUE TITLE
Jedi stopped working after upgrade

### ISSUE THREAD

**Issue by kermit666** [tkf/emacs-jedi#246]
I upgraded all my Python and Emacs packages and Jedi stopped working after this. When I start the editor I get the error:

```
Error (jedi): Failed to start Jedi EPC server.
*** You may need to run "M-x jedi:install-server". ***
This could solve the problem especially if you haven't run the command yet
since Jedi.el installation or update and if the server complains about
Python module imports.
```

When I try to start the server using this command there's an epc error, which after "popping" it shows:

```
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /Users/kermit/.emacs.d/.python-environments/default/bin/python2.7
  Reason: image not found

Process epc:server:5 trace/BPT trap: 5
```

I am starting Emacs the way I always used to with Jedi - open a new editor with the desired virtualenv activated, i.e.

    workon venv; emacs .

This venv has `epc`, `jedi` and Emacs also has all the packages listed on the website. I am running Python 2.7.10 in this particular instance, though it doesn't work with Python 3.5.0 either.

Any idea how I might get Jedi to behave as expected?

**Comment by syohex** [comment]
Could you retry after removing `~/.emacs.d/.python-environments` ?

**Comment by kermit666** [comment]
@syohex, you're a savior! Works like a charm :)

Thanks for the :zap: reply!! Now I can get straight back to comfy work :smile:
