### ISSUE TITLE
Archlinux: Failed to start Jedi EPC server

### ISSUE THREAD

**Issue by all3fox** [tkf/emacs-jedi#247]
``` shell
alex@tardis ~ % emacs --version
GNU Emacs 24.5.1
alex@tardis ~ % python --version
Python 3.5.0
alex@tardis ~ % virtualenv --version
13.1.2
```
Relevant part of my `.emacs`:
```
(require 'epc)
(require 'jedi)
(add-hook 'python-mode-hook 'jedi:setup)
```
After an update today, whenever I open a python module, I get:
```
Error (jedi): Failed to start Jedi EPC server.
*** You may need to run "M-x jedi:install-server". ***
This could solve the problem especially if you haven't run the command yet
since Jedi.el installation or update and if the server complains about
Python module imports.
```
If I run `M-x jedi:install-server`, I get the following:
```
Running: pip install --upgrade /home/alex/.emacs.d/elpa/jedi-core-20150623.2335/...Done
deferred error : (error "Process [/home/alex/.emacs.d/.python-environments/default/bin/pip] exited abnormally : /home/alex/.emacs.d/.python-environments/default/bin/python3: error while loading shared libraries: libpython3.4m.so.1.0: cannot open shared object file: No such file or directory
")
```

As I understand, the problem is that the expected and actual versions of python are different. Please suggest possible ways to fix that.

Thank you for the handy piece of software you are making here.

**Comment by syohex** [comment]
Could you retry after removing `/home/alex/.emacs.d/.python-environments` ?

**Comment by all3fox** [comment]
Meanwhile, I removed the stale `python3.4` virtualenv from my `emacs.d` and ran `jedi:install-server` again. It created a new virtalenv with `python3.5`.

However, currently there is a python import problem. If I do `epc:pop-to-last-server-process-bffer`:
```
Traceback (most recent call last):
  File "/home/alex/.emacs.d/elpa/jedi-core-20150623.2335/jediepcserver.py", line 322, in <module>
    main()
  File "/home/alex/.emacs.d/elpa/jedi-core-20150623.2335/jediepcserver.py", line 316, in main
    server = jedi_epc_server(**vars(ns))
  File "/home/alex/.emacs.d/elpa/jedi-core-20150623.2335/jediepcserver.py", line 224, in jedi_epc_server
    import epc.server
ImportError: No module named 'epc'

Process epc:server:2 exited abnormally with code 1
```

If I do `package-list-packages`, `epc` seems to be installed:
```
  epc                20140609.2234 installed             A RPC stack for the Emacs Lisp
```

So, how should I make `import epc.server` succeed?

**Comment by syohex** [comment]
> ImportError: No module named 'epc'

This is python package. You should do `M-x jedi:install-server` or install dependencies manually(`pip install jedi epc` etc)

**Comment by all3fox** [comment]
Thank you, @syohex 

Unfortnately, the package manager for Archlinux does not seem to have a `python-epc`:

```
alex@tardis ~/ % pacman -Ss epc
extra/libepc 0.4.4-3
    Easy Publish and Consume Library
community/lxlauncher 0.2.4-1 (lxde)
    Open source clone of the Asus launcher for EeePC
```

So, I went into `~/.emacs.d/.python-environments/default` and did the following:
``` sh
alex@tardis ~/.emacs.d/.python-environments/default % touch ./bin/activate
alex@tardis ~/.emacs.d/.python-environments/default % pip install epc
```
That, weirdly, gave me a permission error. So I asked with `sudo` and it worked.

I can confirm that autocompletion now works for me. However, please note that currently updating `jedi` on Archlinux is bumpy. Thanks for your time, marking as closed.
