### ISSUE TITLE
 (depends-on "auto-complete")... this is bad for company-mode users

### ISSUE THREAD

**Issue by shackra** [tkf/emacs-jedi#248]
Package.el has installed auto-complete for emacs-jedi despite the fact I use company-mode and company-jedi.

Having two auto completion frameworks working on Emacs at the same time makes things really awkward...

BTW, turning off auto-complete just makes emacs-jedi not to work.

**Comment by syohex** [comment]
Please don't install `jedi` for company users. You should install only `company-jedi`(and its dependency `jedi-core` which is installed when installing `company-jedi` as dependency). And Cask file is only for testing, users need not to use it.

**Comment by shackra** [comment]
ouh, I see
