### ISSUE TITLE
Failed to enable logging 

### ISSUE THREAD

**Issue by shiyuangu** [tkf/emacs-jedi#251]
Hi, 
I tried to enable jedi server logging by 
(setq jedi:server-args '("--log /home/sgu/tmp/jedi.log"))
but failed with error 

```
jediepcserver.py: error: unrecognized arguments: --log /home/sgu/tmp/jedi.log
Process epc:server:2 exited abnormally with code 2
```

If I directly run jediepcserver.py with the same argument in the terminal, it runs without errors. 
Except the logging problem, Jedi-emacs works well for me.  What is the correct way to turn on the logging? I want to see what jedi python api is called when an jedi-elisp function is called.  Will I see this info from the logging? Thank you.

**Comment by syohex** [comment]
> (setq jedi:server-args '("--log /home/sgu/tmp/jedi.log"))

`jedi:server-args` must be list of string. So please try again with following code. 

```lisp
(setq jedi:server-args '("--log" "/home/sgu/tmp/jedi.log"))
```

**Comment by shiyuangu** [comment]
Yes, this solves the problem. Thank you!
