### ISSUE TITLE
 Flicker / extraneous output in echo area and *Messages*

### ISSUE THREAD

**Issue by davidswelt** [tkf/emacs-jedi#253]
Whenever I type the name of a variable that cannot be found, the echo line flickers (momentarily enlarges to accommodate extra output) and then shows "nil". Messages shows:

no Python documentation found for 'a'

nil
Expected behavior: if documentation cannot be found, do not output anything in the echo area as not to distract the user.

Just installed version 0.2.6 from MELPA.
Python mode 6.2.0.
Aquamacs 3.x development version. Can't get it to work on basic Emacs 25.1.

**Comment by syohex** [comment]
Could you show us the code which reproduces this issue ?

**Comment by davidswelt** [comment]
You mean the Python code?

Just make a new buffer, M-x python-mode, then type

print a

It tries to find the object for “a”, which fails.

**Comment by syohex** [comment]
> You mean the Python code?

Yes. Thanks, I'll check this issue.

**Comment by syohex** [comment]
And could you show us your python version and emacs-jedi configuration ?

**Comment by davidswelt** [comment]
Python 2.7.10 (default, Aug 22 2015, 20:33:39) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)] on darwin

emacs-jedi 0.2.6
I have not configured it beyond the defaults I get when installing via MELPA-stable.

Aquamacs 3.3dev (based on Emacs 25.1 branch)

It’s enough to just type “a” into a new python-mode buffer to provoke the flicker.

**Comment by syohex** [comment]
> emacs-jedi 0.2.6 I have not configured it beyond the defaults I get when installing via MELPA-stable.

It's strange. emacs-jedi does nothing without configuration. If you use auto-complete, you need to call `jedi:setup`. Or if you use company, you need to set company-backends.

```lisp
;; auto-complete
(add-hook 'python-mode #'jedi:setup)

;; company-mode
(defun my/python-mode-hook ()
  (add-to-list 'company-backends 'company-jedi))

(add-hook 'python-mode-hook 'my/python-mode-hook)
```

> no Python documentation found for 'a'

And I suppose this is error message of `pydoc`. You can get this message by typing `pydoc a` in terminal emulator such as Terminal.app, iTerm2 etc. However jedi never use `pydoc`.

I think this is [python-mode](https://gitlab.com/python-mode-devs/python-mode) issue(This python-mode is not bundled Emacs). python-mode has the code which calls pydoc with at cursor word.

Please report this issue to https://gitlab.com/python-mode-devs/python-mode/issues

**Comment by davidswelt** [comment]
OK, that’s progress for this bug (even if it’s not a JEDI bug.)  Thanks for the troubleshooting.

**Comment by Yevgnen** [comment]
@davidswelt I don't use python-mode, but I have the same issue just like yours.
