### ISSUE TITLE
Socket issues

### ISSUE THREAD

**Issue by distantstar** [tkf/emacs-jedi#260]
Hi guys,

I installed Jedi from melpa packages using the following to .emacs:

```
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)
```

I installed Jedi issuing the following to Emacs:

`M-x packages-install jedi`

And after opening python file, I get the error:

> Error (jedi): Failed to start Jedi EPC server.
> *** You may need to run "M-x jedi:install-server". ***
> This could solve the problem especially if you haven't run the command yet
> since Jedi.el installation or update and if the server complains about
> Python module imports.

So, I issue the command:

`M-x jedi:install-server`

But now, I keep getting the following error:

> Traceback (most recent call last):
>   File "/home/distantstar/.emacs.d/.python-environments/default/bin/jediepcserver", line 11, in <module>
>     sys.exit(main())
>   File "/home/distantstar/.emacs.d/.python-environments/default/lib/python2.7/site-packages/jediepcserver.py", line 321, in main
>     server = jedi_epc_server(**vars(ns))
>   File "/home/distantstar/.emacs.d/.python-environments/default/lib/python2.7/site-packages/jediepcserver.py", line 230, in jedi_epc_server
>     server = epc.server.EPCServer((address, port))
>   File "/home/distantstar/.emacs.d/.python-environments/default/lib/python2.7/site-packages/epc/server.py", line 121, in __init__
>     self, server_address, RequestHandlerClass, bind_and_activate)
>   File "/usr/lib64/python2.7/SocketServer.py", line 420, in __init__
>     self.server_bind()
>   File "/usr/lib64/python2.7/SocketServer.py", line 434, in server_bind
>     self.socket.bind(self.server_address)
>   File "/usr/lib64/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> socket.error: [Errno 99] Cannot assign requested address
> 
> Process epc:server:2 exited abnormally with code 1
> 

I don't know what else I need to provide to aid you guys. Oh, some background information, I'm on Gentoo Linux and using Emacs-24.5. 

>   epc                20140609.2234 installed             A RPC stack for the Emacs Lisp
>   jedi               20151214.705  installed             a Python auto-completion for Emacs
>   jedi-core          20151214.705  installed             Common code of jedi.el and company-jedi.el
>   jedi-direx         20140310.236  installed             Tree style source code viewer for Python buffer
>   python-environment 20150310.153  installed             virtualenv API for Emacs Lisp

Let me know what other information you need.

**Comment by syohex** [comment]
> socket.error: [Errno 99] Cannot assign requested address

This error message means you already bind the EPC server port. Please try again after some minutes. And please report me if you reproduce this issue.

**Comment by distantstar** [comment]
Looks like I am no longer seeing the error message after trying again after some time. Thanks for the help!
