### ISSUE TITLE
jedi:install-server tries to pip-install from elisp source directory

### ISSUE THREAD

**Issue by hmeine** [tkf/emacs-jedi#261]
I have el-get-install'ed jedi-core.  Now, when I run jedi:install-server, I am getting:

    Running: pip install --upgrade /Users/hmeine/Library/Preferences/Aquamacs Emacs/Packages/el-get/jedi-core/...Done
    deferred error : (error "Process [/Users/hmeine/.python-environments/default/bin/pip] exited abnormally : Directory '/Users/hmeine/Library/Preferences/Aquamacs Emacs/Packages/el-get/jedi-core/' is not installable. File 'setup.py' not found.

Maybe jedi-core.el is supposed to live alongside setup.py, but the jedi-core recipy only installs the single .el file (see https://github.com/dimitri/el-get/pull/2338 ).  I would suggest to pass a repository URL to pip install, probably only conditionally after checking whether setup.py is present along the .el.

**Comment by hmeine** [comment]
For people with similar errors: I could work around this using

    (setq jedi:source-dir "https://github.com/tkf/emacs-jedi/archive/v0.2.7.zip")

before trying to use jedi (indirectly through company, that is).

**Comment by syohex** [comment]
Please try following el-get configuration instead of official recipe.


```lisp
(el-get-bundle tkf/emacs-jedi
  :load ("jedi-core.el")
  :name jedi-core
  :depends (epc python-environment))

(el-get-bundle company-jedi
  :depends (company-mode))
```

**Comment by hmeine** [comment]
This looks great, being so much less verbose.  Having found a working solution, and currently trying other completion options, do you still want me to try that?  If so, do I have to perform all of the following?

* put the (el-get-bundle stuff into my .emacs
* el-get-remove jedi-core and company-jedi, and jedi (which I installed again in the meantime)?
* remove the two .rcp files?
* el-get-install the two
* test completion (with ac and jedi deactivated / removed)

BTW: couldn't company-jedi just :depends on jedi-core as well?

**Comment by syohex** [comment]
>    put the (el-get-bundle stuff into my .emacs

Yes

>    el-get-remove jedi-core and company-jedi, and jedi (which I installed again in the meantime)?

Yes

>    remove the two .rcp files?

No. You need not to remove them.

>    el-get-install the two

You need only to evaluate them(`C-x C-e= etc)

>    test completion (with ac and jedi deactivated / removed)

Yes

> BTW: couldn't company-jedi just :depends on jedi-core as well?

I don't understand el-get well. I don't know whether its `jedi-core`refers original `jedi-core` recipe or my `jedi-core` recipe.

**Comment by hmeine** [comment]
I can only confirm that your el-get-bundle commands worked, in the sense that jedi-core and company-jedi were successfully installed.  Unfortunately, I could not get them to work.  I think jedi-core still pulls auto-completion as dependency, and AC gets activated by el-get, even without any customized variables or .emacs entries.  For now, I gave up and will try with AC instead of company, which seems to be better supported ATM.

**Comment by syohex** [comment]
Or use following configuration.

```lisp
(el-get-bundle elpa:jedi-core)
(el-get-bundle company-jedi
	       :depends (company-mode))
```

**Comment by hmeine** [comment]
As I said, I already tried again.  I even completely removed my el-get directory and started from scratch.  Since this is my production system, I cannot afford more testing at the moment.  I am sorry about that.

**Comment by nicholascarroll** [comment]
I have this - same issue as #188

**Comment by syohex** [comment]
See https://github.com/tkf/emacs-jedi/issues/188#issuecomment-243779365
