### ISSUE TITLE
emacs-jedi causes weird linum behaviour

### ISSUE THREAD

**Issue by soupault** [tkf/emacs-jedi#262]
Hi!

See attached video - http://s000.tinyupload.com/index.php?file_id=01751954111457247190 .

Without jedi hook for Python in my emacs config everything about linum works without any flaws.

[show-setup-info.txt](https://github.com/tkf/emacs-jedi/files/169850/show-setup-info.txt)

**Comment by syohex** [comment]
auto-complete does not work with linum-mode well. Could you add following configuration and retry ?

```
(ac-linum-workaround)
```

**Comment by soupault** [comment]
@syohex This helped. Thanks a lot!
