### ISSUE TITLE
unable to install emacs-jedi

### ISSUE THREAD

**Issue by Dauth** [tkf/emacs-jedi#269]
having some issues with installing emacs. below is the error code. What should i do to rectify this problem?

Making virtualenv at c:\Users\Owner\AppData\Roaming\.emacs.d\.python-environments\default...Done
deferred error : (error "Process [virtualenv] exited abnormally : ")

Windows user here

**Comment by syohex** [comment]
Please install [virtualenv](https://pypi.python.org/pypi/virtualenv/) and retry.

**Comment by Dauth** [comment]
virtualenv is already installed.

**Comment by syohex** [comment]
Can you use virtualenv from Emacs ?

**Comment by Dauth** [comment]
how do i use it? new Emacs user here so i am not too sure

**Comment by syohex** [comment]
1. `M-x shell-command`
2. `virtualenv --version`

If you get some error like `command not found`, you need to set PATH environment.

**Comment by Dauth** [comment]
(Shell command failed with code 1 and no output)
This is my error which differs from yours. any idea on how to get more information on what error it is?

**Comment by syohex** [comment]
1. `M-x ielm`
2. `(executable-find "virtualenv")

If you get `nil`, virtualenv is not in your PATH.

BTW where did you install pip ? And did you set its path in PATH environment variable ?

**Comment by Dauth** [comment]
did not receive a nil. 
This was the result  "d:/install location/python/Scripts/virtualenv.exe"
I have also added the below path which contains pip.exe to the environment of windows
"D:\python3\Scripts"
