### ISSUE TITLE
issues on completion of "re" module

### ISSUE THREAD

**Issue by oracleyue** [tkf/emacs-jedi#272]
It fails to complete `re` module, as illustrated below
![screen shot 2016-06-02 at 19 17 45](https://cloud.githubusercontent.com/assets/5046605/15754082/c4b52c34-28f6-11e6-98f3-4e8aac48b32a.png)

And I have also check that `jedi` does complete `re`, shown as below. It implies it could be a bug of `emacs-jedi`. Please check it, maybe I did something wrong. I remember it works before.
Any ideas? Many thanks!

INFO:
    OS: OS X
    Emacs: 24.5.1
    Jedi: 0.9.0
    emacs jedi: jedi-20160425.2156
    emacs jedi-core: jedi-core-20160501.2043

```
In [1]: import jedi

In [2]: source = '''import re
re.
'''

In [3]: script = jedi.Script(source, 2, len('re.'), 'example.py')

In [4]: completions = script.completions()

In [5]: completions
Out[5]: 
[<Completion: compile>,
 <Completion: copy_reg>,
 <Completion: DEBUG>,
 <Completion: DOTALL>,
 <Completion: error>,
 <Completion: escape>,
 <Completion: findall>,
 <Completion: finditer>,
 <Completion: I>,
 <Completion: IGNORECASE>,
 <Completion: L>,
 <Completion: LOCALE>,
 <Completion: M>,
 <Completion: match>,
 <Completion: MULTILINE>,
 <Completion: purge>,
 <Completion: S>,
 <Completion: Scanner>,
 <Completion: search>,
 <Completion: split>,
 <Completion: sre_compile>,
 <Completion: sre_parse>,
 <Completion: sub>,
 <Completion: subn>,
 <Completion: sys>,
 <Completion: T>,
 <Completion: template>,
 <Completion: TEMPLATE>,
 <Completion: U>,
 <Completion: UNICODE>,
 <Completion: VERBOSE>,
 <Completion: X>,
 <Completion: _alphanum>,
 <Completion: _cache>,
 <Completion: _cache_repl>,
 <Completion: _compile>,
 <Completion: _compile_repl>,
 <Completion: _expand>,
 <Completion: _locale>,
 <Completion: _MAXCACHE>,
 <Completion: _pattern_type>,
 <Completion: _pickle>,
 <Completion: _subx>,
 <Completion: __all__>,
 <Completion: __doc__>,
 <Completion: __file__>,
 <Completion: __name__>,
 <Completion: __package__>,
 <Completion: __version__>]
```

**Comment by syohex** [comment]
I cannot reproduce this issue.

![jedi-re](https://cloud.githubusercontent.com/assets/554281/15776074/8172a8c8-29c0-11e6-9939-1116908c9572.png)

Each version information is here.
```lisp
(:emacs-version "24.5.1" :jedi-version "0.2.7")
((:file nil :name "sys" :version "3.5.1+ (default, Mar 30 2016, 22:46:26) \n[GCC 5.3.1 20160330]")
 (:file "/home/syohei/.virtualenv/lib/python3.5/site-packages/jedi/__init__.py" :name "jedi" :version "0.9.0")
 (:file "/home/syohei/.virtualenv/lib/python3.5/site-packages/epc/__init__.py" :name "epc" :version "0.0.5")
 (:file "/home/syohei/.virtualenv/lib/python3.5/site-packages/sexpdata.py" :name "sexpdata" :version "0.0.3"))
```

**Comment by oracleyue** [comment]
@syohex May I ask for your configuration of jedi in your emacs? Many thanks!

**Comment by oracleyue** [comment]
@syohex Even when I use such a simple configuration, shown in the figure, it still not works. It implies either I had problems in compiling `jediepcserver` or python+module setup.

FYI, I use `pip install -U PATH/TO/EMACS-JEDI/` to generate `jediepcserver`, which is `Version: 0.2.7`. And it works for `os` and `json` (examples in http://tkf.github.io/emacs-jedi/latest/), as shown in figures.
I didn't use `jedi:install-server`, which I am sure about configurations to use`virtualenv` in emacs.

Do you have any further ideas to locate the problem? Many thanks!

OS: OS X 10.10.5  (my ArchLinux machine also fails to work.)
Python: 2.7.11 (homebrew-ed)
Python Packages: installed by pip
- jedi: 0.9.0
- epc:0.0.5
- argparse: 1.4.0
- virtualenv: 12.1.1
Emacs: 24.5.1
- epc: 20140609.2234
- deferred: 20160109.2046
- autocomplete: 20160416.604
- python-environment.el: 20150310.153

![screen shot 2016-06-03 at 15 59 31](https://cloud.githubusercontent.com/assets/5046605/15781211/57e0acb4-29a5-11e6-9298-a34b7094ca3d.png)
![screen shot 2016-06-03 at 16 03 31](https://cloud.githubusercontent.com/assets/5046605/15781216/5a3cb926-29a5-11e6-990a-95bbde0725cc.png)
![screen shot 2016-06-03 at 16 03 57](https://cloud.githubusercontent.com/assets/5046605/15781217/5c058a08-29a5-11e6-9467-2fc049cc145a.png)

**Comment by syohex** [comment]
My configuration is here.

```
(add-hook 'python-mode-hook 'jedi:setup)
```

**Comment by oracleyue** [comment]
@syohex Is it possible to test `jediepcsever` in command line? If possible, could you give an example to test `re.`? Thanks!

**Comment by oracleyue** [comment]
I also use the oneline configuration for `jedi`, and runing `jedi:install-server`. The same problem holds. 
Thus, I think it's a problem on my `jediepcserver`, which then comes from my python and modules setup. On OSX, I am afraid that it is a conflict between OSX-shipped python and my Homebrew-ed python. I will do the same test on my Linux later. Let's see how it works on Linux.

![screen shot 2016-06-03 at 16 56 33](https://cloud.githubusercontent.com/assets/5046605/15782946/7aa979b8-29ac-11e6-8e15-efffe2c9eb35.png)

**Comment by oracleyue** [comment]
@syohex Sorry for disturbing you so long for a stupid mistake!
When I tested it, I was in a workshop. So I carelessly chose `re.py` as a filename. Then of course, when I tested completion, it parse this module first instead of system modules. That's where I got trapped. I didn't notice it and used it for testing all time. It costed me so much time. Sigh.....

However, thanks a lot for your help!
