### ISSUE TITLE
jedi can not show chinese ?

### ISSUE THREAD

**Issue by zhangjie2012** [tkf/emacs-jedi#274]
Look:

![aa](https://cloud.githubusercontent.com/assets/2450412/16609988/973c350a-438a-11e6-9560-70831b42187c.png)

**Comment by syohex** [comment]
Could you show us sample code which reproduces this issue ?
However I confirmed jedi can show Japanese. Did you use UTF-8 encoding ?

![jedi-multibyte](https://cloud.githubusercontent.com/assets/554281/16623026/3b947832-43d7-11e6-85d9-0a0809433fbd.png)

**Comment by zhangjie2012** [comment]
@immerrr 

time too long ... I have change auto-complete to company-mode.  It looks like not show tips ...

![image](https://user-images.githubusercontent.com/2450412/48403003-ea19b080-e767-11e8-90b8-69663be12bfc.png)

**Comment by immerrr** [comment]
@zhangjie2012 https://github.com/expez/company-quickhelp is responsible for showing tooltips in company world. And looks like it works fine with chinese docs.
![screenshot from 2018-11-13 10-37-33](https://user-images.githubusercontent.com/579798/48404325-452fb100-e730-11e8-8149-a65405a70f97.png)
