### ISSUE TITLE
Wrong highlight of function argument

### ISSUE THREAD

**Issue by Yevgnen** [tkf/emacs-jedi#277]
When calling a function with keywords, namely the argument list has `=`, the wrong argument is highlighted and always sticks in the first argument containing `=`. Pleas see the difference below.

<img width="266" alt="screen shot 2016-12-04 at 7 22 34 pm" src="https://cloud.githubusercontent.com/assets/16749790/20865807/0dcb6cca-ba57-11e6-85b0-d42886e95159.png">
<img width="266" alt="screen shot 2016-12-04 at 7 22 43 pm" src="https://cloud.githubusercontent.com/assets/16749790/20865808/0ec33e6e-ba57-11e6-861a-2961cb072a7d.png">

**Comment by syohex** [comment]
Thanks for reporting issue. However this is jedi issue, not emacs-jedi. emacs-jedi uses result of `call_signatures` API. So if jedi is fixed, then this issue is fixed.

**Comment by Yevgnen** [comment]
@syohex Thanks for your reply!
