### ISSUE TITLE
jedi from projects's virtualenv is used instead of jedi from the emacs-jedi environment

### ISSUE THREAD

**Issue by spookylukey** [tkf/emacs-jedi#290]
(Snipped long explanation, as I realised from https://github.com/davidhalter/jedi/issues/36#issuecomment-10333374 that @tkf understands the issue).

jediepcserver should be using the `Script(sys_path=...)` argument that appears to have been added in jedi 0.10 - see https://jedi.readthedocs.io/en/latest/docs/plugin-api.html#jedi.api.Script -  instead of adding to the process's own `sys.path`. This would isolate the emacs-jedi installation from whatever happens to be in the virtualenv of the project we are working on.

Of course, this can only be done once if we require using jedi 0.10 or later.

In the future, this would have the effect that breakages such as #283 would be a bit less of an issue, since you would be able to have a different (incompatible) version of jedi within a project's virtualenv without breaking emacs-jedi.

**Comment by spookylukey** [comment]
Having upgraded to latest version, I now can't reproduce a situation where I can break emacs-jedi by installing a broken/different jedi version inside the project's virtualenv.

However, there is still an issue - if I do `import jedi` in a project (or `import epc`, or anything else required by jediepcserver etc.), and use `jedi:goto-definition`, then I arrive at the version inside `~/.emacs.d/.python-environments`, instead of the one in the virtualenv.

**Comment by spookylukey** [comment]
See #291

**Comment by immerrr** [comment]
This issue should be fixed with the current master. Could you try it?

**Comment by spookylukey** [comment]
@immerrr - yes, seems to be all good now, thanks!

**Comment by immerrr** [comment]
Great, closing
