### ISSUE TITLE
popup and company? 

### ISSUE THREAD

**Issue by fxfactorial** [tkf/emacs-jedi#307]
Does popup work with company-jedi ? I'm not getting popups based on latest version from elpa

**Comment by articuluxe** [comment]
auto-complete (which uses popup) and company are competing frameworks that don’t work together.

**Comment by immerrr** [comment]
This repo only contains a backend implementation for `auto-complete` and not `company`. You probably need to ask around at https://github.com/syohex/emacs-company-jedi. To avoid conflicts between the two frameworks, make sure you *don't invoke* `jedi:ac-setup` in your configuration.
