### ISSUE TITLE
Can't get completion for non built-in modules

### ISSUE THREAD

**Issue by liushihao456** [tkf/emacs-jedi#313]
I have python3.7 installed by homebrew and when I work in python files, I have completion for math, matplotlib, etc, but I can't have completion as expected for numpy, pandas, etc. It seems that it only supports built-in packages of python.

Firtst I thought I need to install these packages in the virtual env that jedi made. However, when I activate the virtualenv in .python-environments/default and type "pip install numpy" in terminal, it returns the message that "Requirement already satisfied: numpy in /usr/local/lib/python3.7/site-packages (1.15.0)".

The following is my configuration:
`(use-package jedi-core
  :ensure t
  :ensure company-jedi
  :hook (python-mode . jedi:setup)
  :config
  (message "Jedi loaded.")
  (setq jedi:complete-on-dot t)
  (setq jedi:use-shortcuts t)

  (make-local-variable 'company-backends)
  (setq company-backends nil)
  (add-to-list 'company-backends 'company-jedi)

  ;; make sure the company backends are set again when opening another python file.
  (defun my/jedi-setup ()
    "Add company-jedi to company-backends in python mode."
    (make-local-variable 'company-backends)
    (setq company-backends nil)
    (add-to-list 'company-backends '(company-jedi company-yasnippet company-files))
    )
  (add-hook 'python-mode-hook 'my/jedi-setup)
  )`

Could you tell me how to solve this problem? I have looked all over the internet and didn't find a successful solution.

**Comment by noelfarrugia09** [comment]
I have the same problem and described it here https://emacs.stackexchange.com/questions/43874/emacs-company-jedi-python3-auto-completion

**Comment by liushihao456** [comment]
I tried jedi with auto-complete instead of company, and everything works, the completion for everything,  and also the tooltip popups( it seems like with company the tooltips simply don't show up, that's another problem I had), etc. 

I really don't understand why this difference. But for now I think maybe I will work with auto-complete.

**Comment by noelfarrugia09** [comment]
Can you share your setup please? Because I tried it using the auto-complete package and it still did not work? Could be I'm configuring something incorrectly.

**Comment by liushihao456** [comment]
Sure. The following is my configuration. It's simple and it really works out of the box.

(use-package jedi
  :ensure t
  :custom (jedi:complete-on-dot t)
  :hook (python-mode . jedi:ac-setup)
  )

I didn't activate the other features such as jump-to-definitions etc, if you need them just replace "jedi:ac-setup" by "jedi:setup". It's all in the documentation. :)

**Comment by noelfarrugia09** [comment]
Thank you! 👍

**Comment by InspectorMustache** [comment]
Python 3.7 isn't supported by Jedi yet and it will fall back to the next highest installed version which is probably 2.7. In that case you can see third-party packages but only those installed for 2.7. (I posted a more elaborate answer at [that StackOverflow post](https://emacs.stackexchange.com/questions/43874/emacs-company-jedi-python3-auto-completion/44191#44191)).

Then again, since this is an issue with Jedi, switching to auto-complete should make no difference with regards to completions not working. So there might be something else going on here.
