### ISSUE TITLE
How to use python3 for jedi:goto-definition?

### ISSUE THREAD

**Issue by abo-abo** [tkf/emacs-jedi#329]
I have this config that should make Jedi work with Python3:

```elisp
(setq python-environment-virtualenv
        '("virtualenv" "--system-site-packages" "--quiet" "--python" "/usr/bin/python3"))
```

However when I do `jedi:goto-definition` on this code:

```python
import os
```

it gives me: `/usr/lib/python2.7/os.py`.

I would like instead for it to give `/usr/lib/python3.6/os.py`. How can I configure this?

This is also a pain for when I try goto-definition for packages installed with `pip3`: Jedi will say they're not installed because it looks only for `pip2` packages.

**Comment by immerrr** [comment]
This is a variable for `python-environment` package for when it creates new environments. It is possible that jedi already has created a virtualenv for itself and it contains python2. Could you check the environment pointed to by `(python-environment-root-path jedi:environment-root)`?

You can also try `jedi:reinstall-server`, it will remove that environment and recreate it from scratch.

**Comment by abo-abo** [comment]
Here's what I have:

```
~/.emacs.d/.python-environments/jedi/bin:
jediepcserver
pip
pip3
pip3.6
python -> python3
python3
python3.6 -> python3
```

so it's already using python3. The issue is how it connects to existing system packages. It should connect to `/usr/lib/python3.6/`, but it connects to `/usr/lib/python2.7`.

**Comment by immerrr** [comment]
Could you share your `jedi:show-setup-info` and `jedi:show-version-info`?

**Comment by abo-abo** [comment]
`jedi:show-version-info`:

```elisp
(:emacs-version "26.1" :jedi-version "0.2.7")
((:version "2.7.15+ (default, Oct  2 2018, 22:12:08) \n[GCC 8.2.0]" :name "sys" :file nil)
 (:version "0.13.1" :name "jedi" :file "/usr/local/lib/python2.7/dist-packages/jedi/__init__.pyc")
 (:version "0.0.5" :name "epc" :file "/usr/local/lib/python2.7/dist-packages/epc/__init__.pyc")
 (:version "0.0.3" :name "sexpdata" :file "/usr/local/lib/python2.7/dist-packages/sexpdata.pyc"))
```

So it's using Python2. How can I make it use Python3?

**Comment by abo-abo** [comment]
OK, problem solved with:

```elisp
(setq jedi:server-command (list "python3" jedi:server-script))
```

The default `jedi:server-command` was using "python". Thanks for pointing me in the right direction.

**Comment by immerrr** [comment]
:+1: you are most welcome
