### ISSUE TITLE
New release on Emacs package repositories?

### ISSUE THREAD

**Issue by apiraino** [tkf/emacs-jedi#336]
Hello!

I'm using the release from Melpa which is more than 4 years old. While it works really great, would be much work a 2019 release from master? Same could apply to Melpa stable / Marmalade.

Thanks for this wonderful Emacs extension!

EDIT: just realized there's a `jedi-core`, latest release is 20181207

**Comment by immerrr** [comment]
Yes, there's a bit of confusion potential in this repository.

`jedi-core` package is what covers the communication between Emacs and a jedi sidecar server. `jedi-core` is then used as a dependency for `company-jedi` which implements a completion backend for `company` and `jedi` which implements a completion backend for `auto-complete`. Both `jedi-core` and `jedi` are provided by files from this repository, `jedi-core.el` and `jedi.el` files respectively.

Melpa (without stable) is supposed to create releases automatically when there's a change registered in source files, so it is expected that the last release for `jedi-core` is from last December and the last release for `jedi` is from 2016, that is when those files were last updated.

And yes, I guess emacs-jedi could use a fresh release in melpa stable.

**Comment by apiraino** [comment]
ok, thanks for clarifying! If you want I can leave this issue open as a reminder, otherwise feel free to close it :+1:

**Comment by immerrr** [comment]
Fresh v0.2.8 release is online at http://stable.melpa.org/#/jedi-core
