### ISSUE TITLE
Does this plugin support dynamic/runtime auto-completion for type/variable/function names?

### ISSUE THREAD

**Issue by hongyi-zhao** [tkf/emacs-jedi#351]
Hi,

Does this plugin support dynamic/runtime auto-completion for type/variable/function names, just
as the behavior showed by ipython/jupyter?

I focused on dynamic/runtime analysis to offer completion just as the
problem discussed [here](https://ask.wingware.com/question/1728/tab-completion-only-available-when-entering-the-debug-mode-for-some-python-packages/).

More specifically, I want to have the feature/behavior similar to work
interactively in the Python Shell. That way it should report
what is actually there at runtime, as does any shell like iPython.

I'm not sure whether emacs-jedi has the expected feature mentioned above. Any hints are highly appreciated.

Regards,
HY

**Comment by immerrr** [comment]
Hi,

In general, I don't think so, emacs-jedi only shows what jedi returns to it. jedi focuses first and foremost on the _static_ analysis of the code, and emacs-jedi does not do anything to prepare a runtime environment for dynamic completions. IIRC, there were some corner cases in which jedi executed the code, e.g. for builtin modules, but that was always an exception to the rule, and might have changed.

**Comment by hongyi-zhao** [comment]
Thanks for your comments. If so, do you know whether there are some other plugins which meet requirements I mentioned here?

**Comment by immerrr** [comment]
Looks like elpy does that: https://elpy.readthedocs.io/en/latest/ide.html#option-elpy-get-info-from-shell

**Comment by hongyi-zhao** [comment]
Thanks for letting me know this. I've tried to confirm this [feature](https://github.com/jorgenschaefer/elpy/issues/1847) to its developer.

**Comment by asmeurer** [comment]
Jedi does have an API for interactive REPL completion https://jedi.readthedocs.io/en/latest/docs/api.html#interpreter
