### ISSUE TITLE
binding broken with jedi >= 0.18

### ISSUE THREAD

**Issue by parisni** [tkf/emacs-jedi#352]
jedi v 0.18 have removed deprecated signatures such goto-definition / assignement
(see https://jedi.readthedocs.io/en/latest/docs/changelog.html#id1)

then the binding is broken (workaround: keep jedi 0.17.2)

**Comment by glyph** [comment]
I just hit this, goto-definition provokes `deferred error : (error "\"AttributeError(\\\"type object 'Script' has no attribute 'goto_assignments'\\\")\"")`

**Comment by pagabuc** [comment]
I am not sure if this is the correct way to downgrade the jedi package, but this did the trick for me:
```
 ~/.emacs.d/.python-environments/default/bin/pip install jedi==0.17.2
```
