### ISSUE TITLE
Strange message with native compilation

### ISSUE THREAD

**Issue by paaguti** [tkf/emacs-jedi#362]
emacs28-0-91 compiled today. I get the following message when I get the package and compile it on my system:

```
Warning (comp): jedi.el:95:16: Warning: looking-back called with 1 argument, but requires 2-3 Disable showing Disable logging
```

**Comment by immerrr** [comment]
Thank you for the report, should be fixed with cbe59175c3c7769225b1255a2f5369429fac2f31. Please, see if it works for you.
