### ISSUE TITLE
'Symbol' object has no attribute 'value'

### ISSUE THREAD

**Issue by glyph** [tkf/emacs-jedi#368]
I upgraded some emacs packages today and started getting this behavior from Jedi:

```
>> Connection start: localhost:51243
>> Connection establish
>> SEND : ["000047(call 47 add_path_to_index \"/Users/glyph/Projects/Pomodouroboros/src\")
"]
INCOMING: [epc con 46] ["00004e(epc-error () \"AttributeError(\\\"'Symbol' object has no attribute 'value'\\\")\")
"]
<< RECV [(epc-error nil "AttributeError(\"'Symbol' object has no attribute 'value'\")")]
SIG EPC-ERROR: (epc-error (nil "AttributeError(\"'Symbol' object has no attribute 'value'\")"))
RET-EPC-ERR: NOT FOUND: id:nil ["AttributeError(\"'Symbol' object has no attribute 'value'\")"]
```

Given the commit date on this repository and my fairly regular package update schedule I'm guessing that this is downstream somewhere, perhaps `epc` or `deferred`, but I figured I'd report it here for tracking

**Comment by glyph** [comment]
I can't include any additional information easily because `jedi:show-version-info` is also broken by whatever changed.

**Comment by glyph** [comment]
Pinning sexpdata for now has worked around this for me, so https://github.com/jd-boyd/sexpdata/issues/36 is definitely the cause.

**Comment by pawciobiel** [comment]
this duplicates  [#348](https://github.com/tkf/emacs-jedi/issues/348)

**Comment by glyph** [comment]
Closing as a duplicate, then.
