### ISSUE TITLE
Fix keybinds and how it is configured

### ISSUE THREAD

**Issue by tkf** [tkf/emacs-jedi#47]
> I agree that the current approach won't scale well.  I think we should provide (1) conventional keybinds that are allowed for minor mode by default and (2) a variable to on/off non-conventional shortcut that may override global binding (like `M-.`, `M-*`).  But nothing in between (i.e., one variable per keybind).  So, Emacs beginners can turn it on easily enough, but no complication for normal Emacs users.
> -- https://github.com/tkf/emacs-jedi/issues/42#issuecomment-16873478

See discussions in #42 and #44.

**Comment by madhavan020985** [comment]
@asmeurer, i was struggling with this command
````elisp
(setq jedi:use-shortcuts t)
````
it didn't work, after reading your comment, i tried
````elisp
(setq jedi:use-shortcuts t)
````
it burped attempt to set a constant symbol: t, and go-to-definition worked beautifully. Isn't jedi:use-shortcuts like any other global variable?

**Comment by asmeurer** [comment]
That is the exact line that I have in my .emacs and it works.
