### ISSUE TITLE
goto-definition(C-c dot) cannot navigate to definition in different module if original file is opened using Tramp

### ISSUE THREAD

**Issue by bingxiao1** [tkf/emacs-jedi#89]
Open a remote python file (foo.py) using tramp

foo.py:
from bar import bar

Now try to go to definition of "bar" using "C-c ."

Expected: emacs opens definition of bar
Actual: get "Definition not found"

The navigation works if I ssh to the remote host and use jedi from emacs session on the remote host

**Comment by syohex** [comment]
You should use `sshfs`, if you use this feature for remote file.

**Comment by jaseemabid** [comment]
@syohex Its a workaround, which might not be always possible.
